@startuml
class RVBankOptions {
    + CurrentSection : RVBankSection <<get>> <<set>>
    + DecompressionTimeout : TimeSpan <<get>> <<set>>
    + CompressionErrorsAreWarnings : bool <<get>> <<set>>
    + RequireValidSignature : bool <<get>> <<set>> = true
    + RequireEmptyVersionMeta : bool <<get>> <<set>> = true
    + RequireFirstEntryIsVersion : bool <<get>> <<set>>
    + WriteValidOffsets : bool <<get>> <<set>>
    + AllowMultipleVersion : bool <<get>> <<set>>
    + FlatRead : bool <<get>> <<set>> = true
    + AlwaysSeparateOnDummy : bool <<get>> <<set>> = true
    + IgnoreDuplicateFiles : bool <<get>> <<set>> = true
    + RegisterEmptyEntries : bool <<get>> <<set>> = true
    + AllowObfuscated : bool <<get>> <<set>>
    + AllowEncrypted : bool <<get>> <<set>>
    + AllowVersionMimeOnData : bool <<get>> <<set>>
    + AllowUnnamedDataEntries : bool <<get>> <<set>> = true
    + IgnoreInvalidStreamSize : bool <<get>> <<set>>
    + IgnoreEntryWhenLZSSOverflow : bool <<get>> <<set>>
    + RequireVersionNotNamed : bool <<get>> <<set>> = true
    + RemoveBenignProperties : bool <<get>> <<set>> = true
    + RequireVersionMimeOnVersion : bool <<get>> <<set>> = true
    + RespectEntryOffsets : bool <<get>> <<set>> = false
    + AsciiLengthTimeout : int <<get>> <<set>> = 250
    + Charset : Encoding <<get>> <<set>>
    + ByteOrder : Endianness <<get>> <<set>>
    + IgnoreValidation : bool <<get>> <<set>>
}
IBinarizationOptions <|-- RVBankOptions
IAsciizLimiterOptions <|-- RVBankOptions
@enduml
