//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/ryannkelly/Desktop/BisUtils/BisUtils.Generated/BisUtils.Generated.ParamLang/ParamParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BisUtils.Generated.ParamLang;

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IParamParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ParamParserBaseListener : IParamParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.computationalStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComputationalStart([NotNull] ParamParser.ComputationalStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.computationalStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComputationalStart([NotNull] ParamParser.ComputationalStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclaration([NotNull] ParamParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclaration([NotNull] ParamParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumValue([NotNull] ParamParser.EnumValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.enumValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumValue([NotNull] ParamParser.EnumValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] ParamParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] ParamParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.arrayAppension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAppension([NotNull] ParamParser.ArrayAppensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.arrayAppension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAppension([NotNull] ParamParser.ArrayAppensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.arrayTruncation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayTruncation([NotNull] ParamParser.ArrayTruncationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.arrayTruncation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayTruncation([NotNull] ParamParser.ArrayTruncationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.deleteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleteStatement([NotNull] ParamParser.DeleteStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.deleteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleteStatement([NotNull] ParamParser.DeleteStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.externalClassDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternalClassDeclaration([NotNull] ParamParser.ExternalClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.externalClassDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternalClassDeclaration([NotNull] ParamParser.ExternalClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] ParamParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] ParamParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDeclaration([NotNull] ParamParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDeclaration([NotNull] ParamParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.tokenDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTokenDeclaration([NotNull] ParamParser.TokenDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.tokenDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTokenDeclaration([NotNull] ParamParser.TokenDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.literalArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralArray([NotNull] ParamParser.LiteralArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.literalArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralArray([NotNull] ParamParser.LiteralArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.literalString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralString([NotNull] ParamParser.LiteralStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.literalString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralString([NotNull] ParamParser.LiteralStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.literalInteger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralInteger([NotNull] ParamParser.LiteralIntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.literalInteger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralInteger([NotNull] ParamParser.LiteralIntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.literalFloat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralFloat([NotNull] ParamParser.LiteralFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.literalFloat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralFloat([NotNull] ParamParser.LiteralFloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.literalOrArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralOrArray([NotNull] ParamParser.LiteralOrArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.literalOrArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralOrArray([NotNull] ParamParser.LiteralOrArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] ParamParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] ParamParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.arrayName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayName([NotNull] ParamParser.ArrayNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.arrayName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayName([NotNull] ParamParser.ArrayNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ParamParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] ParamParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ParamParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] ParamParser.IdentifierContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
