//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/ryannkelly/Desktop/BisUtils/BisUtils.Generated/BisUtils.Generated.EnScript/EnScriptParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BisUtils.Generated.EnScript;
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="EnScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IEnScriptParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.computationalStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComputationalStart([NotNull] EnScriptParser.ComputationalStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.computationalStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComputationalStart([NotNull] EnScriptParser.ComputationalStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclaration([NotNull] EnScriptParser.TypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclaration([NotNull] EnScriptParser.TypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalDeclaration([NotNull] EnScriptParser.GlobalDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.globalDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalDeclaration([NotNull] EnScriptParser.GlobalDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.globalInheritance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobalInheritance([NotNull] EnScriptParser.GlobalInheritanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.globalInheritance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobalInheritance([NotNull] EnScriptParser.GlobalInheritanceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumDeclaration([NotNull] EnScriptParser.EnumDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumDeclaration([NotNull] EnScriptParser.EnumDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumBody([NotNull] EnScriptParser.EnumBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumBody([NotNull] EnScriptParser.EnumBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.enumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumMember([NotNull] EnScriptParser.EnumMemberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.enumMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumMember([NotNull] EnScriptParser.EnumMemberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] EnScriptParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] EnScriptParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] EnScriptParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] EnScriptParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.funcOrVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncOrVar([NotNull] EnScriptParser.FuncOrVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.funcOrVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncOrVar([NotNull] EnScriptParser.FuncOrVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.funcVarOrDeconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncVarOrDeconstructor([NotNull] EnScriptParser.FuncVarOrDeconstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.funcVarOrDeconstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncVarOrDeconstructor([NotNull] EnScriptParser.FuncVarOrDeconstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] EnScriptParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] EnScriptParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarator([NotNull] EnScriptParser.VariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.variableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarator([NotNull] EnScriptParser.VariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.undefinedVariableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUndefinedVariableDeclarator([NotNull] EnScriptParser.UndefinedVariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.undefinedVariableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUndefinedVariableDeclarator([NotNull] EnScriptParser.UndefinedVariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.definedVariableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinedVariableDeclarator([NotNull] EnScriptParser.DefinedVariableDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.definedVariableDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinedVariableDeclarator([NotNull] EnScriptParser.DefinedVariableDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] EnScriptParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] EnScriptParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.deconstructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeconstructorDeclaration([NotNull] EnScriptParser.DeconstructorDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.deconstructorDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeconstructorDeclaration([NotNull] EnScriptParser.DeconstructorDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionDeclarationParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclarationParameters([NotNull] EnScriptParser.FunctionDeclarationParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionDeclarationParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclarationParameters([NotNull] EnScriptParser.FunctionDeclarationParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionDeclarationDefinedParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclarationDefinedParameter([NotNull] EnScriptParser.FunctionDeclarationDefinedParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionDeclarationDefinedParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclarationDefinedParameter([NotNull] EnScriptParser.FunctionDeclarationDefinedParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionDeclarationUndefinedParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclarationUndefinedParameter([NotNull] EnScriptParser.FunctionDeclarationUndefinedParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionDeclarationUndefinedParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclarationUndefinedParameter([NotNull] EnScriptParser.FunctionDeclarationUndefinedParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionBody([NotNull] EnScriptParser.FunctionBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionBody([NotNull] EnScriptParser.FunctionBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.encapsulatedFunctionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEncapsulatedFunctionBody([NotNull] EnScriptParser.EncapsulatedFunctionBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.encapsulatedFunctionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEncapsulatedFunctionBody([NotNull] EnScriptParser.EncapsulatedFunctionBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] EnScriptParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] EnScriptParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionCallParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallParameters([NotNull] EnScriptParser.FunctionCallParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionCallParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallParameters([NotNull] EnScriptParser.FunctionCallParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionCallParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallParameter([NotNull] EnScriptParser.FunctionCallParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionCallParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallParameter([NotNull] EnScriptParser.FunctionCallParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] EnScriptParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] EnScriptParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] EnScriptParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] EnScriptParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.primaryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryStatement([NotNull] EnScriptParser.PrimaryStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.primaryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryStatement([NotNull] EnScriptParser.PrimaryStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.foreachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeachStatement([NotNull] EnScriptParser.ForeachStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.foreachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeachStatement([NotNull] EnScriptParser.ForeachStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.foreachControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeachControl([NotNull] EnScriptParser.ForeachControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.foreachControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeachControl([NotNull] EnScriptParser.ForeachControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] EnScriptParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] EnScriptParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForControl([NotNull] EnScriptParser.ForControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.forControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForControl([NotNull] EnScriptParser.ForControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] EnScriptParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] EnScriptParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] EnScriptParser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] EnScriptParser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.objectCreation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectCreation([NotNull] EnScriptParser.ObjectCreationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.objectCreation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectCreation([NotNull] EnScriptParser.ObjectCreationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] EnScriptParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] EnScriptParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.threadStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThreadStatement([NotNull] EnScriptParser.ThreadStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.threadStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThreadStatement([NotNull] EnScriptParser.ThreadStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotoStatement([NotNull] EnScriptParser.GotoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotoStatement([NotNull] EnScriptParser.GotoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.deleteStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteStatement([NotNull] EnScriptParser.DeleteStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.deleteStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteStatement([NotNull] EnScriptParser.DeleteStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.lambdaStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaStatement([NotNull] EnScriptParser.LambdaStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.lambdaStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaStatement([NotNull] EnScriptParser.LambdaStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] EnScriptParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] EnScriptParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] EnScriptParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] EnScriptParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] EnScriptParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] EnScriptParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchStatement([NotNull] EnScriptParser.SwitchStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.switchStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchStatement([NotNull] EnScriptParser.SwitchStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchLabel([NotNull] EnScriptParser.SwitchLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.switchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchLabel([NotNull] EnScriptParser.SwitchLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.defaultSwitchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefaultSwitchLabel([NotNull] EnScriptParser.DefaultSwitchLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.defaultSwitchLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefaultSwitchLabel([NotNull] EnScriptParser.DefaultSwitchLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] EnScriptParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] EnScriptParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] EnScriptParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] EnScriptParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.negatedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNegatedExpression([NotNull] EnScriptParser.NegatedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.negatedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNegatedExpression([NotNull] EnScriptParser.NegatedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.parenthesisedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesisedExpression([NotNull] EnScriptParser.ParenthesisedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.parenthesisedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesisedExpression([NotNull] EnScriptParser.ParenthesisedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.arrayIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayIndex([NotNull] EnScriptParser.ArrayIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.arrayIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayIndex([NotNull] EnScriptParser.ArrayIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralString([NotNull] EnScriptParser.LiteralStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralString([NotNull] EnScriptParser.LiteralStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralBoolean([NotNull] EnScriptParser.LiteralBooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralBoolean([NotNull] EnScriptParser.LiteralBooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralNull([NotNull] EnScriptParser.LiteralNullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralNull([NotNull] EnScriptParser.LiteralNullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralArray([NotNull] EnScriptParser.LiteralArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralArray([NotNull] EnScriptParser.LiteralArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalNumeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralNumeric([NotNull] EnScriptParser.LiteralNumericContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalNumeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralNumeric([NotNull] EnScriptParser.LiteralNumericContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalFloat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralFloat([NotNull] EnScriptParser.LiteralFloatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalFloat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralFloat([NotNull] EnScriptParser.LiteralFloatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalInteger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralInteger([NotNull] EnScriptParser.LiteralIntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalInteger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralInteger([NotNull] EnScriptParser.LiteralIntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] EnScriptParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] EnScriptParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.genericTypeDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericTypeDeclarationList([NotNull] EnScriptParser.GenericTypeDeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.genericTypeDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericTypeDeclarationList([NotNull] EnScriptParser.GenericTypeDeclarationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.genericTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericTypeDeclaration([NotNull] EnScriptParser.GenericTypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.genericTypeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericTypeDeclaration([NotNull] EnScriptParser.GenericTypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.genericTypedReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericTypedReference([NotNull] EnScriptParser.GenericTypedReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.genericTypedReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericTypedReference([NotNull] EnScriptParser.GenericTypedReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.typeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeReference([NotNull] EnScriptParser.TypeReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.typeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeReference([NotNull] EnScriptParser.TypeReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.typeModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeModifier([NotNull] EnScriptParser.TypeModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.typeModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeModifier([NotNull] EnScriptParser.TypeModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.sharedFuncOrVarModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSharedFuncOrVarModifiers([NotNull] EnScriptParser.SharedFuncOrVarModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.sharedFuncOrVarModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSharedFuncOrVarModifiers([NotNull] EnScriptParser.SharedFuncOrVarModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableModifier([NotNull] EnScriptParser.VariableModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.variableModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableModifier([NotNull] EnScriptParser.VariableModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionModifier([NotNull] EnScriptParser.FunctionModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionModifier([NotNull] EnScriptParser.FunctionModifierContext context);
}
