//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/ryannkelly/Desktop/BisUtils/BisUtils.Generated/BisUtils.Generated.EnScript/EnScriptParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace BisUtils.Generated.EnScript;

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEnScriptParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class EnScriptParserBaseListener : IEnScriptParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.computationalStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComputationalStart([NotNull] EnScriptParser.ComputationalStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.computationalStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComputationalStart([NotNull] EnScriptParser.ComputationalStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclaration([NotNull] EnScriptParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclaration([NotNull] EnScriptParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalDeclaration([NotNull] EnScriptParser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.globalDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalDeclaration([NotNull] EnScriptParser.GlobalDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.globalInheritance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalInheritance([NotNull] EnScriptParser.GlobalInheritanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.globalInheritance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalInheritance([NotNull] EnScriptParser.GlobalInheritanceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumDeclaration([NotNull] EnScriptParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.enumDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumDeclaration([NotNull] EnScriptParser.EnumDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumBody([NotNull] EnScriptParser.EnumBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.enumBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumBody([NotNull] EnScriptParser.EnumBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.enumMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumMember([NotNull] EnScriptParser.EnumMemberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.enumMember"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumMember([NotNull] EnScriptParser.EnumMemberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDeclaration([NotNull] EnScriptParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.classDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDeclaration([NotNull] EnScriptParser.ClassDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] EnScriptParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] EnScriptParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.funcOrVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncOrVar([NotNull] EnScriptParser.FuncOrVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.funcOrVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncOrVar([NotNull] EnScriptParser.FuncOrVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.funcVarOrDeconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncVarOrDeconstructor([NotNull] EnScriptParser.FuncVarOrDeconstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.funcVarOrDeconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncVarOrDeconstructor([NotNull] EnScriptParser.FuncVarOrDeconstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] EnScriptParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] EnScriptParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarator([NotNull] EnScriptParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.variableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarator([NotNull] EnScriptParser.VariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.undefinedVariableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUndefinedVariableDeclarator([NotNull] EnScriptParser.UndefinedVariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.undefinedVariableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUndefinedVariableDeclarator([NotNull] EnScriptParser.UndefinedVariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.definedVariableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefinedVariableDeclarator([NotNull] EnScriptParser.DefinedVariableDeclaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.definedVariableDeclarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefinedVariableDeclarator([NotNull] EnScriptParser.DefinedVariableDeclaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaration([NotNull] EnScriptParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaration([NotNull] EnScriptParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.deconstructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeconstructorDeclaration([NotNull] EnScriptParser.DeconstructorDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.deconstructorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeconstructorDeclaration([NotNull] EnScriptParser.DeconstructorDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionDeclarationParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclarationParameters([NotNull] EnScriptParser.FunctionDeclarationParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionDeclarationParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclarationParameters([NotNull] EnScriptParser.FunctionDeclarationParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionDeclarationDefinedParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclarationDefinedParameter([NotNull] EnScriptParser.FunctionDeclarationDefinedParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionDeclarationDefinedParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclarationDefinedParameter([NotNull] EnScriptParser.FunctionDeclarationDefinedParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionDeclarationUndefinedParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclarationUndefinedParameter([NotNull] EnScriptParser.FunctionDeclarationUndefinedParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionDeclarationUndefinedParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclarationUndefinedParameter([NotNull] EnScriptParser.FunctionDeclarationUndefinedParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionBody([NotNull] EnScriptParser.FunctionBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionBody([NotNull] EnScriptParser.FunctionBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.encapsulatedFunctionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEncapsulatedFunctionBody([NotNull] EnScriptParser.EncapsulatedFunctionBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.encapsulatedFunctionBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEncapsulatedFunctionBody([NotNull] EnScriptParser.EncapsulatedFunctionBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCall([NotNull] EnScriptParser.FunctionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCall([NotNull] EnScriptParser.FunctionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionCallParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCallParameters([NotNull] EnScriptParser.FunctionCallParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionCallParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCallParameters([NotNull] EnScriptParser.FunctionCallParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionCallParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCallParameter([NotNull] EnScriptParser.FunctionCallParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionCallParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCallParameter([NotNull] EnScriptParser.FunctionCallParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute([NotNull] EnScriptParser.AttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.attribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute([NotNull] EnScriptParser.AttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] EnScriptParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] EnScriptParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.primaryStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryStatement([NotNull] EnScriptParser.PrimaryStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.primaryStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryStatement([NotNull] EnScriptParser.PrimaryStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.foreachStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachStatement([NotNull] EnScriptParser.ForeachStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.foreachStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachStatement([NotNull] EnScriptParser.ForeachStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.foreachControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeachControl([NotNull] EnScriptParser.ForeachControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.foreachControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeachControl([NotNull] EnScriptParser.ForeachControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] EnScriptParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] EnScriptParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForControl([NotNull] EnScriptParser.ForControlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.forControl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForControl([NotNull] EnScriptParser.ForControlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] EnScriptParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] EnScriptParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] EnScriptParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] EnScriptParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.objectCreation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectCreation([NotNull] EnScriptParser.ObjectCreationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.objectCreation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectCreation([NotNull] EnScriptParser.ObjectCreationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] EnScriptParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] EnScriptParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.threadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThreadStatement([NotNull] EnScriptParser.ThreadStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.threadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThreadStatement([NotNull] EnScriptParser.ThreadStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.gotoStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotoStatement([NotNull] EnScriptParser.GotoStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.gotoStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotoStatement([NotNull] EnScriptParser.GotoStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.deleteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeleteStatement([NotNull] EnScriptParser.DeleteStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.deleteStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeleteStatement([NotNull] EnScriptParser.DeleteStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.lambdaStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaStatement([NotNull] EnScriptParser.LambdaStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.lambdaStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaStatement([NotNull] EnScriptParser.LambdaStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] EnScriptParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] EnScriptParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] EnScriptParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] EnScriptParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] EnScriptParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] EnScriptParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatement([NotNull] EnScriptParser.SwitchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatement([NotNull] EnScriptParser.SwitchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchLabel([NotNull] EnScriptParser.SwitchLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.switchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchLabel([NotNull] EnScriptParser.SwitchLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.defaultSwitchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultSwitchLabel([NotNull] EnScriptParser.DefaultSwitchLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.defaultSwitchLabel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultSwitchLabel([NotNull] EnScriptParser.DefaultSwitchLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] EnScriptParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] EnScriptParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpression([NotNull] EnScriptParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpression([NotNull] EnScriptParser.PrimaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.negatedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegatedExpression([NotNull] EnScriptParser.NegatedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.negatedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegatedExpression([NotNull] EnScriptParser.NegatedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.parenthesisedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesisedExpression([NotNull] EnScriptParser.ParenthesisedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.parenthesisedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesisedExpression([NotNull] EnScriptParser.ParenthesisedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.arrayIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayIndex([NotNull] EnScriptParser.ArrayIndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.arrayIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayIndex([NotNull] EnScriptParser.ArrayIndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralString([NotNull] EnScriptParser.LiteralStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralString([NotNull] EnScriptParser.LiteralStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralBoolean([NotNull] EnScriptParser.LiteralBooleanContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalBoolean"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralBoolean([NotNull] EnScriptParser.LiteralBooleanContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralNull([NotNull] EnScriptParser.LiteralNullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralNull([NotNull] EnScriptParser.LiteralNullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralArray([NotNull] EnScriptParser.LiteralArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralArray([NotNull] EnScriptParser.LiteralArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalNumeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralNumeric([NotNull] EnScriptParser.LiteralNumericContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalNumeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralNumeric([NotNull] EnScriptParser.LiteralNumericContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalFloat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralFloat([NotNull] EnScriptParser.LiteralFloatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalFloat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralFloat([NotNull] EnScriptParser.LiteralFloatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.literalInteger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralInteger([NotNull] EnScriptParser.LiteralIntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.literalInteger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralInteger([NotNull] EnScriptParser.LiteralIntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] EnScriptParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] EnScriptParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.genericTypeDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericTypeDeclarationList([NotNull] EnScriptParser.GenericTypeDeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.genericTypeDeclarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericTypeDeclarationList([NotNull] EnScriptParser.GenericTypeDeclarationListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.genericTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericTypeDeclaration([NotNull] EnScriptParser.GenericTypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.genericTypeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericTypeDeclaration([NotNull] EnScriptParser.GenericTypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.genericTypedReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericTypedReference([NotNull] EnScriptParser.GenericTypedReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.genericTypedReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericTypedReference([NotNull] EnScriptParser.GenericTypedReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeReference([NotNull] EnScriptParser.TypeReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeReference([NotNull] EnScriptParser.TypeReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.typeModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeModifier([NotNull] EnScriptParser.TypeModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.typeModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeModifier([NotNull] EnScriptParser.TypeModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.sharedFuncOrVarModifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSharedFuncOrVarModifiers([NotNull] EnScriptParser.SharedFuncOrVarModifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.sharedFuncOrVarModifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSharedFuncOrVarModifiers([NotNull] EnScriptParser.SharedFuncOrVarModifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableModifier([NotNull] EnScriptParser.VariableModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.variableModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableModifier([NotNull] EnScriptParser.VariableModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EnScriptParser.functionModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionModifier([NotNull] EnScriptParser.FunctionModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EnScriptParser.functionModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionModifier([NotNull] EnScriptParser.FunctionModifierContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
