@startuml
class RVBankDirectoryExtensions <<static>> {
    + {static} GetEntries(ctx:IRVBankDirectory) : IEnumerable<T>
    + {static} GetEntries(ctx:IRVBankDirectory, mime:RVBankEntryMime) : IEnumerable<IRVBankEntry>
    + {static} GetEntries(ctx:IRVBankDirectory, name:string) : IEnumerable<IRVBankEntry>
    + {static} GetDirectories(ctx:IRVBankDirectory, option:SearchOption) : IEnumerable<IRVBankDirectory>
    + {static} GetDirectory(ctx:IRVBankDirectory, name:string, option:SearchOption) : IRVBankDirectory?
    + {static} GetDataEntries(ctx:IRVBankDirectory, option:SearchOption) : IEnumerable<IRVBankDataEntry>
    + {static} GetDataEntries(ctx:IRVBankDirectory, name:string, option:SearchOption) : IEnumerable<IRVBankDataEntry>
    + {static} IsEmpty(ctx:IRVBankDirectory) : bool
    + {static} GetVersionEntries(ctx:IRVBankDirectory, option:SearchOption) : IEnumerable<IRVBankVersionEntry>
    + {static} GetVersionEntry(ctx:IRVBankDirectory, option:SearchOption) : IRVBankVersionEntry?
    - {static} VersionEntriesFor(directories:IEnumerable<IRVBankDirectory>) : IEnumerable<IRVBankVersionEntry>
    - {static} DataEntriesFor(directories:IEnumerable<IRVBankDirectory>) : IEnumerable<IRVBankDataEntry>
    - {static} EnumerateDirectoryChildren(directories:List<IRVBankDirectory>) : IEnumerable<IRVBankDirectory>
    + {static} CreateVersionEntry(ctx:IRVBankDirectory, logger:ILogger?, reader:BisBinaryReader, options:RVBankOptions) : IRVBankVersionEntry
    + {static} CreateVersionEntry(ctx:IRVBankDirectory, logger:ILogger?, fileName:string, mime:RVBankEntryMime, originalSize:int, offset:int, timeStamp:int, dataSize:int, properties:IEnumerable<IRVBankProperty>?) : IRVBankVersionEntry
    + {static} AddVersionEntry(ctx:IRVBankDirectory, logger:ILogger?, fileName:string, mime:RVBankEntryMime, originalSize:int, offset:int, timeStamp:int, dataSize:int, properties:IEnumerable<IRVBankProperty>?) : IRVBankVersionEntry
    + {static} AddVersionEntry(ctx:IRVBankDirectory, logger:ILogger?, reader:BisBinaryReader, options:RVBankOptions) : IRVBankVersionEntry
    + {static} AddDirectory(ctx:IRVBankDirectory, name:string, node:IRVBank, logger:ILogger?) : IRVBankDirectory
    + {static} GetOrCreateDirectory(ctx:IRVBankDirectory, name:string, node:IRVBank, logger:ILogger?) : IRVBankDirectory
    + {static} RemoveEntry(ctx:IRVBankDirectory, entry:IRVBankEntry) : void
}
@enduml
