@startuml
class RVBankImproperMimeWarning {
    + RVBankImproperMimeWarning(isError:bool, type:Type?)
    + <<override>> AlertName : string? <<get>> <<init>>
    + <<sealed>> <<override>> IsError : bool <<get>> <<set>>
    + <<sealed>> <<override>> AlertScope : Type? <<get>> <<init>>
    + <<override>> Message : string? <<get>> <<set>>
}
WarningBase <|-- RVBankImproperMimeWarning
@enduml
